FROM almalinux:9

ENV course = "Devops with AWS" \
    trainer = "ram" \
    duration ="120"

    ARG username=shiva
    RUN echo "hello world ${username}" > /tmp/devops.txt 
    CMD [ "sleep", "100" ]